export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const ADD_TO_SHOPING_CART = 'ADD_TO_SHOPING_CART'
export  const ADD_GOODS_MODEL = 'ADD_GOODS_MODEL';
export const CLICK_MODEL_BUTTON = 'CLICK_MODEL_BUTTON';
export const GET_GOODS_DATA_SUCCESS = 'GET_GOODS_DATA_SUCCESS';
export const GET_GOODS_DATA_FAILED ='GET_GOODS_DATA_FAILED';

